/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExpandRequestTupleKey {
    #[serde(rename = "relation")]
    pub relation: String,
    #[serde(rename = "object")]
    pub object: String,
}

impl ExpandRequestTupleKey {
    pub fn new(relation: String, object: String) -> ExpandRequestTupleKey {
        ExpandRequestTupleKey { relation, object }
    }
}
