/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Tuple {
    #[serde(rename = "key")]
    pub key: Box<crate::models::TupleKey>,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
}

impl Tuple {
    pub fn new(key: crate::models::TupleKey, timestamp: String) -> Tuple {
        Tuple {
            key: Box::new(key),
            timestamp,
        }
    }
}
