/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TupleChange {
    #[serde(rename = "tuple_key")]
    pub tuple_key: Box<crate::models::TupleKey>,
    #[serde(rename = "operation")]
    pub operation: crate::models::TupleOperation,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
}

impl TupleChange {
    pub fn new(tuple_key: crate::models::TupleKey, operation: crate::models::TupleOperation, timestamp: String) -> TupleChange {
        TupleChange {
            tuple_key: Box::new(tuple_key),
            operation,
            timestamp,
        }
    }
}


