/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TupleKey {
    #[serde(rename = "user")]
    pub user: String,
    #[serde(rename = "relation")]
    pub relation: String,
    #[serde(rename = "object")]
    pub object: String,
    #[serde(rename = "condition", skip_serializing_if = "Option::is_none")]
    pub condition: Option<Box<crate::models::RelationshipCondition>>,
}

impl TupleKey {
    pub fn new(user: String, relation: String, object: String) -> TupleKey {
        TupleKey {
            user,
            relation,
            object,
            condition: None,
        }
    }
}
