/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsersetTreePeriodDifference {
    #[serde(rename = "base")]
    pub base: Box<crate::models::Node>,
    #[serde(rename = "subtract")]
    pub subtract: Box<crate::models::Node>,
}

impl UsersetTreePeriodDifference {
    pub fn new(base: crate::models::Node, subtract: crate::models::Node) -> UsersetTreePeriodDifference {
        UsersetTreePeriodDifference {
            base: Box::new(base),
            subtract: Box::new(subtract),
        }
    }
}


