/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsersetTreePeriodTupleToUserset {
    #[serde(rename = "tupleset")]
    pub tupleset: String,
    #[serde(rename = "computed")]
    pub computed: Vec<crate::models::Computed>,
}

impl UsersetTreePeriodTupleToUserset {
    pub fn new(
        tupleset: String,
        computed: Vec<crate::models::Computed>,
    ) -> UsersetTreePeriodTupleToUserset {
        UsersetTreePeriodTupleToUserset { tupleset, computed }
    }
}
