/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodTupleToUserset {
    #[serde(rename = "tupleset")]
    pub tupleset: Box<crate::models::ObjectRelation>,
    #[serde(rename = "computedUserset")]
    pub computed_userset: Box<crate::models::ObjectRelation>,
}

impl V1PeriodTupleToUserset {
    pub fn new(tupleset: crate::models::ObjectRelation, computed_userset: crate::models::ObjectRelation) -> V1PeriodTupleToUserset {
        V1PeriodTupleToUserset {
            tupleset: Box::new(tupleset),
            computed_userset: Box::new(computed_userset),
        }
    }
}


